language: c

os: linux

matrix:
  include:
  - name: "GCC Debug"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
    before_script:
      - cd ext
      - bash aom.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug -DAVIF_BUILD_AOM=1 ..
    script:
      - make

  - name: "GCC Release"
    compiler: gcc
    addons:
      apt:
        packages:
          - nasm
    before_script:
      - cd ext
      - bash aom.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DAVIF_BUILD_AOM=1 ..
    script:
      - make

  - name: "Clang Debug"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
    before_script:
      - cd ext
      - bash aom.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Debug -DAVIF_BUILD_AOM=1 ..
    script:
      - make

  - name: "Clang Release"
    compiler: clang
    addons:
      apt:
        packages:
          - nasm
    before_script:
      - cd ext
      - bash aom.cmd
      - cd ..
      - mkdir build
      - cd build
      - cmake -DCMAKE_BUILD_TYPE=Release -DAVIF_BUILD_AOM=1 ..
    script:
      - make
