name: CI Android Emulator Tests
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci-android-emulator-tests.yml"
      - "android_jni/**"
  pull_request:
    paths:
      - ".github/workflows/ci-android-emulator-tests.yml"
      - "android_jni/**"

permissions:
  contents: read

# Cancel the workflow if a new one is triggered from the same PR, branch, or tag, except on main.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-run-android-jni-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # This is needed for faster emulators. See:
      # https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Download and Setup the Android NDK
        uses: nttld/setup-ndk@afb4c9964b521afb97c864b7d40b11e6911bd410 # v1.5.0
        id: setup-ndk
        with:
          # r25c is the same as 25.2.9519653.
          ndk-version: r25c
          add-to-path: false
      - uses: ./.github/actions/setup-linux
        with:
          codec-dav1d: "LOCAL"
          libyuv: "LOCAL"
          oldest-cmake: true
      - name: Setup JDK
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Run Instrumented Tests on the Emulator
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d # v2.33.0
        with:
          working-directory: android_jni
          api-level: 31
          force-avd-creation: false
          ndk: 25.2.9519653
          arch: x86_64
          script: ./gradlew cAT
