name: CI Android Emulator Tests
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-android-emulator-tests.yml'
      - 'android_jni/**'
  pull_request:
    paths:
      - '.github/workflows/ci-android-emulator-tests.yml'
      - 'android_jni/**'

permissions:
  contents: read

# Cancel the workflow if a new one is triggered from the same PR, branch, or tag, except on main.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-run-android-jni-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout the repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      # This is needed for faster emulators. See:
      # https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Download and Setup the Android NDK
        uses: nttld/setup-ndk@afb4c9964b521afb97c864b7d40b11e6911bd410 # v1.5.0
        id: setup-ndk
        with:
          # r25c is the same as 25.2.9519653.
          ndk-version: r25c
          add-to-path: false
      - uses: ./.github/actions/setup-linux
        with:
          codec-dav1d: 'LOCAL'
          libyuv: 'LOCAL'
      - name: Setup JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Instrumented Tests on the Emulator
        uses: reactivecircus/android-emulator-runner@f0d1ed2dcad93c7479e8b2f2226c83af54494915 # v2.32.0
        with:
          working-directory: android_jni
          api-level: 31
          force-avd-creation: false
          ndk: 25.2.9519653
          arch: x86_64
          script: ./gradlew cAT
