name: CI Fuzz
on:
  pull_request:
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/gtest/**'
      - 'tests/oss-fuzz/**'

permissions:
  contents: read

# Cancel the workflow if a new one is triggered from the same PR, branch, or tag, except on main.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@c836f141decccfaa27ef54cd5959faeec3f32bd7 # master
      with:
        oss-fuzz-project-name: 'libavif'
        dry-run: false
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@c836f141decccfaa27ef54cd5959faeec3f32bd7 # master
      with:
        oss-fuzz-project-name: 'libavif'
        fuzz-seconds: 600
        dry-run: false
    - name: Upload Crash
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
